### ISSUE TITLE
Idea: Calculate cost from existing whatif/plan

### ISSUE THREAD

**Issue by reijoh** [TheCloudTheory/arm-estimator#252]
In a CI/CD workflow it is common to generate a plan/what-if for review before allowing apply/deploy. With Azure Cost Estimator this review can now include cost, great. One thing I have noticed in the output when using this estimator is "Waiting for response from What If API". My idea then is, what if the workflow already have this what-if completed and stored in a json file (e.g. az deployment sub what-if --template-file main.json --parameters main.parameters.json --location westeurope --exclude-change-types Ignore NoChange > whatif.json)? Could perhaps Azure Cost Estimator use that json file instead of making a new call to the API?

**Comment by kamil-mrzyglod** [comment]
Hey @reijoh!

ACE caches What-If responses locally (or, when configured, using Azure Storage), so it's able to reuse the same response as long as hash of a template stays the same. What you're proposing, is accepting already existing What-If response, which may be part of existing CICD workflow. I believe I could think about adding such feature, but it'd mean, that it's going to be user's responsibility to provide correct input. Otherwise, the generatest estimation won't be correct :)

**Comment by kamil-mrzyglod** [comment]
https://github.com/TheCloudTheory/arm-estimator/wiki/Options#user-generated-what-if-file
